config/routes.rb
Rails.application.routes.draw do
  get "pins/search"

  resources :pins do
    resources :activities, only: :create
    resources :uploads, only: :destroy
    post "like"
    post "unlike"
  end

  resources :tags, only: :show

  devise_for :users
  resources :users, :only => [:show]
  root "pins#index"
  get "about" => "pages#about" # creates about_path
  get 'wayne' => 'pages#wayne' #creates wayne_path

  post "please_sign_in" => "pages#please_sign_in", :as => :please_sign_in

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_many :activities, :dependent => :destroy
  has_many :uploads, :dependent => :destroy

  has_attached_file :image,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" },
    :s3_protocol => Rails.env.production? ? :https : :http

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  validates :image, presence: true
  validates :title, presence: true
  validates :description, presence: true

  acts_as_taggable_on :tags

  def likes_count
    @likes_count ||= activities.select { |a| a.like? }.count
  end

  def comments_count
    @comments_count ||= activities.reject { |a| a.like? }.count
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  include WelcomeBannerHelper
  include PinFilters
  include BreadcrumbsHelper

  before_action :set_pin, only: [:show, :edit, :update, :destroy, :like, :unlike, :add_attachment]
  before_action :authenticate_user!, except: [:index, :show, :search], unless: :admin_logged_in?
  before_action :correct_user, only: [:edit, :update, :destroy], unless: :admin_logged_in?
  before_action :include_welcome_banner_in_layout!, only: [:index, :search], unless: :user_signed_in?

  crumb(only: [:search, :show, :new, :edit, :create, :update]) do
    ["Projects", pins_path]
  end

  crumb(only: [:show, :edit, :update]) do
    [@pin.title, pin_path(@pin)]
  end

  crumb(only: [:search]) do
    ["\"#{params[:search]}\"", request.fullpath]
  end

  crumb(only: [:index, :search]) do
    view_context.sort_by_link
  end

  def index
    @pins = Pin.all.paginate(:page => params[:page], :per_page => 30).includes(:activities)
    @pins = apply_pin_filters(@pins)
  end

  def search
    conditions = %w[pins.title pins.description tags.name users.name]
    conditions.map! { |column| "UPPER(#{column}) LIKE UPPER(?)" }
    values = conditions.map { "%#{params[:search]}%" }

    @pins = Pin.all.uniq
      .order("pins.created_at DESC")
      .paginate(:page => params[:page], :per_page => 30)
      .includes(:activities)
      .eager_load(:user, :tags)
      .where(conditions.join(" OR "), *values)
  end

  def show
  end

  def new
    crumb("New", pins_path)
    @pin = current_user.pins.build
  end

  def edit
    crumb("Edit", pins_path)
  end

  def create
    crumb("New", pins_path)

    @pin = current_user.pins.build(pin_params)
    if @pin.save
      save_attachments!
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    crumb("Edit", pins_path)

    if @pin.update(pin_params)
      save_attachments!
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  def like
    unless current_user.likes_pin?(@pin)
      @activity = @pin.activities.build(
        :user_id => current_user.id,
        :type => "like"
      )

      @activity.save
    end

    respond_to do |format|
      format.js
    end

    # TODO: handle errors.
    # if @activity.save
    #   render json: @activity, status: :created
    # else
    #   render json: @activity.errors, status: :unprocessable_entity
    # end
  end

  def unlike
    @pin.activities.where(
      :user_id => current_user.id,
      :type => "like"
    ).delete_all

    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.includes(:tags, :uploads => [:user]).find_by(id: params[:pin_id] || params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :image, tag_list: []).tap do |params|
        params[:tag_list] &&= params[:tag_list].join(", ")
      end
    end

    def save_attachments!
      # TODO: prevent other users from uploading.
      return unless params[:attachments]
      params[:attachments].each do |attachment|
        @pin.uploads.create(:attachment => attachment, :user => current_user)
      end
    end

end

app/helpers/pins_helper.rb
module PinsHelper

  def render_pin_card(pin, options = {})
    options[:pin] = pin
    options[:image_size] ||= :medium
    render 'pins/pin_card', options
  end

  def render_new_pin_card
    render 'pins/new_pin_card'
  end

end

app/views/pins/_comment_button.html.erb
<div class="comment-button-container" data-pin-id="<%= pin.id %>">
  <div class="comment-button-inner">
    <%= link_to pin_path(pin) do %>
      <h7 class="comments-count"><%= pin.comments_count %></h7>
      <i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Comments">chat_bubble_outline</i>
    <% end %>
  </div>
</div>

app/views/pins/_form_fields.html.erb
<% if @pin.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

    <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="row">
  <div class="col s12 section">
    <div class="input-field">
      <%= f.text_field :title, class: "validate" %>
      <label for="pin_title">Project Title</label>
    </div>
    <div class="input-field">
      <%= f.text_area :description, class: "validate materialize-textarea" %>
      <label for="pin_description">Project Instructions</label>
    </div>
    <div class="input-field file-field">
      <div class="btn">
        <span>Cover Photo</span>
        <%= f.file_field :image %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    <div class="input-field file-field full-page-hover">
      <div class="btn">
        <span>Add Attachments</span>
        <%= file_field_tag "attachments[]", type: :file, multiple: true %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </div>
</div>

<!--
  <div class="file-field input-field">
    <div class="btn">
      <span>Add Attachments</span>
      <%= f.file_field :upload, multiple: true %>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text" placeholder="Upload one or more files">
    </div>
  </div> -->
<!-- Upload attachment form -->

<div class="row">
  <div class="col s12 section">
    <div class="pin-card-uploads" data-pin-id="<%= @pin.id %>">
      <%= render "uploads/block", :uploads => @pin.uploads.order("created_at DESC") %>
    </div>

    <div class="col s6">
      <div class="tag-list-choices">
        <h6>Lab</h6>
        <% Tag.place.order(:name).all.each do |tag| %>
          <p>
            <%= f.check_box :tag_list, { :multiple => true }, tag.name.downcase, nil %>
            <%= f.label "tag_list_#{tag.name.downcase}".parameterize.underscore, tag.name.downcase %>
          </p>
        <% end %>
      </div>
    </div>
    <div class="col s6">
      <div class="tag-list-choices">
        <h6>Machine(s)</h6>
        <% Tag.machine.order(:name).all.each do |tag| %>
          <p>
            <%= f.check_box :tag_list, { :multiple => true }, tag.name.downcase, nil %>
            <%= f.label "tag_list_#{tag.name.downcase}".parameterize.underscore, tag.name.downcase %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for :card_action do %>
  <%= f.submit class: "btn right", value: "Submit" %>
<% end %>

app/views/pins/_like_button.html.erb
<div class="like-button-container" data-pin-id="<%= pin.id %>">
  <div class="likes-button-inner">
    <% if user_signed_in? %>
      <% if current_user.likes_pin?(pin) %>
        <%= link_to pin_unlike_path(pin), class: "liked", method: :post, :remote => true do %>
          <h7 class="likes-count"><%= pin.likes_count %></h7>
          <i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Likes"> favorite</i>
        <% end %>
      <% else %>
        <%= link_to pin_like_path(pin), class: "unliked", method: :post, :remote => true do %>
          <% unless pin.likes_count.zero? %>
            <h7 class="likes-count"><%= pin.likes_count %></h7>
          <% end %>
          <i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Likes">favorite_border</i>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to please_sign_in_path, class: "unliked", method: :post do %>
        <h7 class="likes-count"><%= pin.likes_count %></h7>
        <i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Likes">favorite_border</i>
        <!-- TODO: Show clickable or already filled in when no user signed in? -->
        <!-- <i class="material-icons">favorite</i> -->
      <% end %>
    <% end %>
  </div>
</div>

app/views/pins/_new_pin_card.html.erb
<%= link_to new_pin_path, class: "new-pin-card box card deep-orange lighten-5 pin-card-sm" do %>

  <div class="card-content center">
    <h5><i class="large material-icons">add_a_photo</i></h5>
    <h5>Add A Project</h5>
  </div>

<% end %>

app/views/pins/_pin_card.html.erb
<div class="box card white pin-card-sm">

  <%= link_to image_tag(pin.image.url(image_size)), pin %>
  <div class="card-content">
    <h5><%= pin.title %></h5>
    <p>by <%= link_to pin.user do %>
      <%= pin.user.name if pin.user %>
      <% end %></p>
  </div>

  <div class="card-action card-options">
    <div class="row">
      <div class="col s3 center-align">
        <%= render 'pins/like_button', pin: pin %>
      </div>

      <div class="col s3 center-align">
        <%= render 'pins/comment_button', pin: pin %>
      </div>

      <% if pin.user == current_user %>
        <div class="col s3 center-align">
          <%= link_to edit_pin_path(pin) do %>
            <i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Edit">create</i>
          <% end %>
        </div>
      <% end %>

      <% if pin.user == current_user %>
        <div class="col s3 center-align">
          <%= link_to pin, method: :delete, data: { confirm: 'Are you sure you want to delete project?' } do %>
            <i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Delete">clear</i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <% if pin.tag_list.any? %>
    <div class="card-action">
      <div class="row">
        <div class="col s12">
          <div class="pin-tags">
            <% pin.tag_list.each do |tag| %>
              <%= link_to tag_path(tag), :class => "chip pin-tag btn" do %>
                <%= tag %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/pins/edit.html.erb
<div class="row">
  <div class="col s12 m8 l6 offset-m2 offset-l3">
    <div class="card white">
      <%= form_for @pin, html: { multipart: true } do |f| %>

        <div class="card-content black-text">
          <span class="card-title">
            <h1 class="center">Editing Project</h1>
          </span>

          <%= render 'form_fields', f: f %>
        </div>

        <div class="card-action clearfix">
          <%= content_for :card_action %>
          <%= link_to 'Back', @pin, class: "left btn white grey-text" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div class="container">

  <% if user_signed_in? %>
    <div class="fixed-action-btn">
      <%= link_to new_pin_path, class: "btn-floating btn-large red" do %>
        <i class="large material-icons">add_a_photo</i>
      <% end %>
    </div>
  <% end %>

  <div id="pins" class="transitions-enabled">
    <% if user_signed_in? %>
      <%= render_new_pin_card %>
    <% end %>

    <% @pins.each do |pin| %>
      <%= render_pin_card(pin) %>
    <% end %>
  </div>

  <div class="center">
    <%= will_paginate @pins %>
  </div>
</div>

app/views/pins/like.js.erb
$(".like-button-container[data-pin-id=\"<%= @pin.id %>\"]").replaceWith("<%= escape_javascript(render "like_button", pin: @pin) %>");

app/views/pins/new.html.erb
<div class="row">
  <div class="col s12 m8 l6 offset-m2 offset-l3">
    <div class="card white">
      <%= form_for @pin, html: { multipart: true } do |f| %>

        <div class="card-content black-text">
          <span class="card-title">
            <h1 class="center">New Project</h1>
          </span>

          <%= render 'form_fields', f: f %>
        </div>

        <div class="card-action clearfix">
          <%= content_for :card_action %>
          <%= link_to 'Back', pins_path, class: "left btn white grey-text" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/pins/search.html.erb
<div class="container">
  <% if user_signed_in? %>
    <div class="fixed-action-btn">
      <%= link_to new_pin_path, class: "btn-floating btn-large red" do %>
        <i class="large material-icons">add_a_photo</i>
      <% end %>
    </div>
  <% end %>

  <!-- TODO: Make the no results thing more reusable? -->
  <% if @pins.empty? %>
    <h4>No results.</h4>
  <% else %>
    <div id="pins" class="transitions-enabled">
      <% @pins.each do |pin| %>
        <%= render_pin_card(pin) %>
      <% end %>
    </div>
  <% end %>

  <div class="center">
    <%= will_paginate @pins %>
  </div>
</div>

app/views/pins/show.html.erb
<div class="container">
  <div class="card white pin-card-lg">
    <div class="card-content black-text">
      <div class="row">
        <div class="col s12 m5 l5">
          <div class="card-title center">
            <!-- TODO: make this a carousel with all the uploaded images? -->
            <!--   If we do it, you'd probably want to be able to change the order of images -->
            <!-- Alternatively, add the ability to promote one attachment to 'Card Banner' -->
            <%= image_tag @pin.image.url(:large) %>
          </div>
        </div>

        <div class="col s12 m7 l7">
          <div class="row">
            <div class="col s12">
              <h4><%= @pin.title.upcase %></h4>
              <%= render 'pins/like_button', pin: @pin %>

              <p>By
                <%= link_to @pin.user do %>
                  <%= @pin.user.name if @pin.user %>
                <% end %>
              </p>

              <h6><strong>INSTRUCTIONS</strong></h6>
              <%= simple_format(@pin.description) %>
            </div>
          </div>

          <% if @pin.tag_list.any? %>
            <div class="pin-tags">
              <% @pin.tag_list.each do |tag| %>
                <%= link_to tag_path(tag), :class => "chip pin-tag btn" do %>
                  <%= tag %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="pin-card-uploads" data-pin-id="<%= @pin.id %>">
        <%= render "uploads/block", :uploads => @pin.uploads.order("created_at DESC") %>
      </div>

      <div class="row">
        <div class="col s12">
          <div class="divider"></div>
          <h5>Add a comment</h5>
          <%= form_for [@pin, @pin.activities.build] do |f| %>

            <div class="input-field">
              <%= f.text_field :body, placeholder:"Type your comments here!", class: "materialize-textarea" %>
            </div>

            <div class="actions">
              <%= f.hidden_field :type, value: "comment" %>
              <%= f.submit class: "btn", value: "submit" %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col s12">
          <% @pin.activities.includes(:user).order("created_at DESC").each do |activity| %>
            <% if activity.comment? %>
              <p>
                <%= activity.user.name %>: <%= activity.body %> [<%= activity.created_at.to_formatted_s(:long) %>]
              </p>
            <% else %>
              <p>
                <%= activity.user.name %> liked this. [<%= activity.created_at.to_formatted_s(:long) %>]
              </p>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="pin-edit">
        <% if @pin.user == current_user %>
          <%= link_to edit_pin_path(@pin) do %>
            <i class="material-icons">create</i> Edit
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/pins/unlike.js.erb
$(".like-button-container[data-pin-id=\"<%= @pin.id %>\"]").replaceWith("<%= escape_javascript(render "like_button", pin: @pin) %>");