config/routes.rb
Rails.application.routes.draw do
  get "pins/search"

  resources :pins do
    resources :activities, only: :create
    resources :uploads, only: :destroy
    post "like"
    post "unlike"
  end

  resources :tags, only: :show

  devise_for :users
  resources :users, :only => [:show]
  root "pins#index"
  get "about" => "pages#about" # creates about_path
  get 'wayne' => 'pages#wayne' #creates wayne_path

  post "please_sign_in" => "pages#please_sign_in", :as => :please_sign_in

end

app/models/upload.rb
class Upload < ActiveRecord::Base

  # TODO: drill down on allowed content-types.
  ALLOWED_CONTENT_TYPES = %w[
    image/jpg
    image/jpeg
    image/png
    image/gif
    application/x-zip-compressed
    application/zip
  ]

  belongs_to :pin
  belongs_to :user

  has_attached_file :attachment,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>", thumbnail: "60x60#" },
    :s3_protocol => Rails.env.production? ? :https : :http

  validates :attachment, attachment_presence: true
  validates_with AttachmentSizeValidator, attributes: :attachment, less_than: 10.megabytes

  validates_attachment :attachment, content_type: { content_type: ALLOWED_CONTENT_TYPES }

  before_post_process :skip_unless_image

  # Return true if the attachment is an image.
  def image?
    @image ||= !!(attachment_content_type =~ /^image\/.+/)
  end

  private

  def skip_unless_image
    image?
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  include PinsHelper
  before_action :set_pin, only: [:destroy]
  before_action :set_upload, only: [:destroy]
  before_action :correct_user, only: [:destroy], unless: :admin_logged_in?

  def destroy
    @upload.destroy
    redirect_to pin_url(@pin), notice: 'Attachment was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:pin_id])
    end

    def set_upload
      @upload = @pin.uploads.find_by(id: params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:pin_id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

end

app/views/uploads/_block.html.erb
<% uploads.each do |upload| %>
  <div class="upload-block card-panel lime lighten-5">
    <div class="row">
      <div class="col s12 m3 l3">
        <%= link_to upload.attachment.url do %>
          <% if upload.image? %>
            <%= image_tag upload.attachment.url(:thumb) %>
          <% else %>
            <i class="attachment-file-icon material-icons">insert_drive_file</i>
          <% end %>
        <% end %>
      </div>
      <div class="col s12 m9 l9">
        <p>
          <%= link_to pin_upload_path(@pin.id, upload), method: :delete, data: { confirm: 'Are you sure you want to delete attachment?' } do %>
            <i class="material-icons tooltipped upload-delete" data-position="top" data-delay="50" data-tooltip="Delete">clear</i>
          <% end %>
        </p>
        <p class="truncate">
          <%= link_to upload.attachment.url do %>
            <%= upload.attachment_file_name %>
          <% end %>
        </p>

        <p class="note">
          Uploaded by
          <%= link_to casual_user_name(upload.user), user_path(upload.user) %>
          at <%= upload.created_at %>
        </p>

        <p>
          <%= link_to upload.attachment.url do %>
            <i class="material-icons">file_download</i> Download
          <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>