config/routes.rb
Rails.application.routes.draw do
  get "pins/search"

  resources :pins do
    resources :activities, only: :create
    resources :uploads, only: :destroy
    post "like"
    post "unlike"
  end

  resources :tags, only: :show

  devise_for :users
  resources :users, :only => [:show]
  root "pins#index"
  get "about" => "pages#about" # creates about_path
  get 'wayne' => 'pages#wayne' #creates wayne_path

  post "please_sign_in" => "pages#please_sign_in", :as => :please_sign_in

end

app/views/layouts/_breadcrumbs.html.erb
<% if crumbs.any? %>
  <div class="container breadcrumbs-container">
    <div class="col s12">
      <% crumbs.each do |(title, uri)| %>
        <% if uri %>
          <%= link_to title, uri, class: "breadcrumb" %>
        <% else %>
          <span class="breadcrumb"><%= title %></span>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav>
  <div class="container">
    <div class="nav-wrapper">
      <%= link_to "Fab Lab Hub", root_path, class: "navbar-brand" %>
      <a href="#" data-activates="mobile-side-nav" class="button-collapse"><i class="material-icons">menu</i></a>

      <ul class="right hide-on-med-and-down">
        <li>
          <!-- Modal Trigger -->
          <a id="search-modal-trigger" class="modal-trigger" href="#search-modal">
            <i class="material-icons">search</i>
          </a>
        </li>
        <li>
          <%= link_to root_path do %>
            Home
          <% end %>
        </li>
        <li>
          <a class="dropdown-button" href="#" data-activates="fablabs"><!-- <i class="material-icons left">public</i> --> Fab Labs</a>
          <!-- Dropdown Structure -->
          <ul id="fablabs" class="dropdown-content">
            <li><%= link_to wayne_path do %>Wayne<% end %></li>
            <li><a>More coming soon!</a></li>
          </ul>
        </li>
        <% if user_signed_in? %>
          <li class="navbar-avatar-item">
            <a class="dropdown-button" href="#" data-activates="account">
              <% if current_user.avatar.exists? %>
                <%= image_tag current_user.avatar.url(:tiny), class: "circle navbar-avatar" %>
              <% else %>
                <i class="material-icons left">face</i>
              <% end %>
            </a>
            <ul id="account" class="dropdown-content">
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>

      <ul class="side-nav" id="mobile-side-nav">
        <li class="logo">
          <%= link_to root_path, class: "logo-container" do %>
            <img id="front-page-logo" src="/images/logo.png" />
          <% end %>
        </li>
        <li class="search card">
          <form action="<%= pins_search_path %>">
            <div class="input-field clearable-input-field">
              <input id="mobile-side-nav-search" name="search" type="search" required>
              <label for="mobile-side-nav-search"><i class="material-icons">search</i></label>
              <i class="material-icons clear-button">close</i>
            </div>
          </form>
        </li>
        <li>
          <%= link_to root_path, class: "collapsible-header" do %>
            <i class="material-icons left">home</i> Home
          <% end %>
        </li>
        <li class="no-padding">
          <ul class="collapsible collapsible-accordion">
            <li>
              <a class="collapsible-header"><i class="material-icons left">public</i> Fab Labs</a>
              <div class="collapsible-body">
                <ul>
                  <li><%= link_to wayne_path do %>Wayne<% end %></li>
                  <li><a>More coming soon!</a></li>
                </ul>
              </div>
            </li>
            <% if user_signed_in? %>
              <li class="navbar-avatar-mobile">
                <a class="collapsible-header">
                  <% if current_user.avatar.exists? %>
                    <%= image_tag current_user.avatar.url(:tiny), class: "circle left responsive-img" %> Account
                  <% else %>
                    <i class="material-icons left">face</i> Account
                  <% end %>
                </a>
                <div class="collapsible-body">
                  <ul>
                    <li><%= link_to "View Profile", user_path(current_user) %></li>
                    <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                  </ul>
                </div>
              </li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- Modal Structure -->
<div id="search-modal" class="modal">
  <div class="modal-content">
    <nav>
      <div class="nav-wrapper">
        <form action="<%= pins_search_path %>">
          <div class="input-field clearable-input-field">
            <input id="search" name="search" type="search" required>
            <label for="search"><i class="material-icons">search</i></label>
            <i class="material-icons clear-button">close</i>
          </div>
        </form>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/_window_variables.html.erb
window.railsEnv = "<%= Rails.env %>";
window.googleAnalyticsTrackingID = "<%= ENV["GOOGLE_ANALYTICS_TRACKING_ID"] %>";

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Fab Lab Hub @ Saint-Gobain</title>
  <script>
    <%= render 'layouts/window_variables' %>
  </script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!--Import Google Icon Font-->
  <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

</head>
<body>

  <%= render 'layouts/header' %>

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name} card-panel") %>
  <% end %>

  <% if flash.empty? && user_signed_in? && !current_user.complete_profile? && !current_page?(edit_user_registration_path) %>
    <%= content_tag(:div, class: "alert alert-nice card-panel") do %>
      <%= link_to edit_user_registration_path do %>
        <div class="valign-wrapper">
          Click here to complete your profile
          <i class="material-icons valign">tag_faces</i>
        </div>
      <% end %>
    <% end %>
  <% end %>

  <%= render 'pages/home' if render_welcome_banner? %>
  <%= render 'layouts/breadcrumbs' %>

  <%= yield %>

  <script>ga('send', 'pageview', window.location.pathname);</script>

</body>
</html>